### PR TITLE
Update wasmtime* crates to 19.0.2

### PR DESCRIPTION
**Pull request by fgsch**
I wanted to have an idea of how much effort, at least superficially, was required to update Viceroy.
The tests are passing but beyond that this is mostly mechanical and untested.

Addresses #360 and I believe is required for #357.

### CODE REVIEW

**Review by jameysharp — APPROVED** [review]
I can confirm that the guest-profiler change here is valid: there's an opportunity to collect more data and produce even more useful profiles, but as written this PR preserves the existing behavior, which is good enough.

I'm less sure about switching from `wasmtime-wasi` to `wasi-common`. My impression is that `wasi-common` is becoming deprecated, but I'm not certain of that.

**Comment by jameysharp** [comment]
Oh, and if we want to note anything about user-visible changes in Viceroy release notes, upgrading to Wasmtime 18 or newer gets us name demangling in guest-profiler output, which is a nice quality of life improvement when profiling Rust services especially.

**Comment by fgsch** [comment]
>[..]
> I'm less sure about switching from `wasmtime-wasi` to `wasi-common`. My impression is that `wasi-common` is becoming deprecated, but I'm not certain of that.

Thanks for having a look. I will check this and update the PR accordingly.

**Comment by elliottt** [comment]
Do you mind if we close this in favor of #366? I've made the `wasmtime-wasi` switch in that PR as well.

**Comment by fgsch** [comment]
Closed in favour of #366

**Pull request closed without merging**
