### PR TITLE
📦 Release Viceroy 0.2.6

### PR DESCRIPTION
**Pull request by aturon**
See changelog for details.

### CODE REVIEW

**Review by cratelyn — COMMENTED** [review]
:heavy_check_mark: looks good to tag!

**Comment by aturon** [comment]
Release published, @cratelyn can you sign off on the version bump and I'll merge?

**Comment by cratelyn** [comment]
note to @aturon: i've added commits 4064a54 and dba7cbd to this branch to (a) fix the CI failures, and (b) expand the `RELEASING.md` instructions slightly to describe how to update _all_ of the lockfiles. i have been bitten by this as well. :heart_decoration:

**Review by cratelyn — APPROVED** [review]
:sparkles: :heavy_check_mark:

**Pull request merged**
