### PR TITLE
🚀 `0.2.10` release

### PR DESCRIPTION
**Pull request by cratelyn**
changes included:

- add telemetry for wall-clock duration ([#121](https://github.com/fastly/Viceroy/pull/121))
- bump various runtime limits ([#123](https://github.com/fastly/Viceroy/pull/123))

### CODE REVIEW

**Comment by cratelyn** [comment]
note: once this is published, we can close #122.

**Review by aturon — DISMISSED** [review]

**Comment by cratelyn** [comment]
:label: tag `v0.2.10` has been pushed, CI is running here: https://github.com/fastly/Viceroy/actions/runs/1813827520

**Comment by cratelyn** [comment]
cc: @aturon, [4101202](https://github.com/fastly/Viceroy/pull/126/commits/41012029731fab5fc43d409bce538eb26d2f246a) and [91c7f83](https://github.com/fastly/Viceroy/pull/126/commits/91c7f83497b341ad457c6482e00b125cfaf7fead) polish a thankfully benign wrinkle in the release process.

we have not published any breaking changes yet, so this thankfully hasn't caused us any trouble. that said, we should nonetheless be sure to update the version of `viceroy-lib` depended on by `viceroy` when publishing new releases.

**Comment by cratelyn** [comment]
```
Warning: Cache service responded with [4](https://github.com/fastly/Viceroy/runs/5113894374?check_suite_focus=true#step:17:4)00 during chunk upload.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:[5](https://github.com/fastly/Viceroy/runs/5113894374?check_suite_focus=true#step:17:5)) {
  errno: -40[8](https://github.com/fastly/Viceroy/runs/5113894374?check_suite_focus=true#step:17:8)3,
  code: 'EBADF',
  syscall: 'read'
}
```

:raised_eyebrow: i'm hoping this is a transient failure of some sort. i've clicked "_re-run_" for now.

**Review by aturon — APPROVED** [review]

**Pull request merged**
